<?php

//  $Id:$
//  ------------------------------------------------------------------------ //
//  XooNIps Online Simulator Item Type Module                                //
//                                                                           //
//  Copyright (C) 2011-2013 RIKEN BSI Neuroinformatics Japan Center          //
//  All rights reserved.                                                     //
//  http://sim.neuroinf.jp/                                                  //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

if (!defined('XOOPS_ROOT_PATH')) {
    exit();
}

$modversion['name'] = _MI_XNPONLINESIMULATION_NAME;
$modversion['version'] = 3.49;
$modversion['description'] = _MI_XNPONLINESIMULATION_DESC;
$modversion['credits'] = 'RIKEN, Japan (http://www.riken.jp/)';
$modversion['author'] = 'Simulation Platform Committee (http://sim.neuroinf.jp/)';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/xnponlinesimulation_slogo.png';
$modversion['dirname'] = 'xnponlinesimulation';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
$modversion['tables'][0] = 'xnponlinesimulation_item_detail';

// Admin things
$modversion['hasAdmin'] = 0;

// Menu
$modversion['hasMain'] = 0;

// Templates
$modversion['templates'][1]['file'] = 'xnponlinesimulation_main.css';
$modversion['templates'][1]['description'] = 'main css';
$modversion['templates'][2]['file'] = 'xnponlinesimulation_top_block.html';
$modversion['templates'][2]['description'] = 'top block';
$modversion['templates'][3]['file'] = 'xnponlinesimulation_list_block.html';
$modversion['templates'][3]['description'] = 'list block';
$modversion['templates'][4]['file'] = 'xnponlinesimulation_register_block.html';
$modversion['templates'][4]['description'] = 'register block';
$modversion['templates'][5]['file'] = 'xnponlinesimulation_detail_block.html';
$modversion['templates'][5]['description'] = 'detail block';
$modversion['templates'][6]['file'] = 'xnponlinesimulation_confirm_block.html';
$modversion['templates'][6]['description'] = 'confirm block';
$modversion['templates'][7]['file'] = 'xnponlinesimulation_search_block.html';
$modversion['templates'][7]['description'] = 'search block';
$modversion['templates'][8]['file'] = 'xnponlinesimulation_embed_block.html';
$modversion['templates'][8]['description'] = 'embed block html';
$modversion['templates'][9]['file'] = 'xnponlinesimulation_export.xml';
$modversion['templates'][9]['description'] = 'export xml';
$modversion['templates'][10]['file'] = 'xnponlinesimulation_oaipmh_oai_dc.xml';
$modversion['templates'][10]['description'] = 'OAI-PMH oai_dc';
$modversion['templates'][11]['file'] = 'xnponlinesimulation_oaipmh_junii2.xml';
$modversion['templates'][11]['description'] = 'OAI-PMH junii2';

// Blocks
$modversion['blocks'][1]['name'] = _MI_XNPONLINESIMULATION_RELATED_ITEM;
$modversion['blocks'][1]['file'] = 'xnponlinesimulation_related_list.php';
$modversion['blocks'][1]['class'] = 'xnponlinesimulationRelated';
$modversion['blocks'][1]['template'] = 'xnponlinesimulation_related_block.html';

// Install script
$modversion['onInstall'] = 'include/oninstall.inc.php';
$modversion['onUpdate'] = 'include/onupdate.inc.php';
$modversion['onUninstall'] = 'include/onuninstall.inc.php';
